import { randomBytes } from "node:crypto";
import bcrypt from "bcryptjs";
import { getToken } from "next-auth/jwt";
import type { NextRequest } from "next/server";
import { assignCohort, getPool, newId } from "@learn-ai/db";
import { ApiError } from "@/lib/http/api-error";
import { sendVerificationEmail } from "./mailer";

/**
 * LEARN_AI_V1_BUILD_SPEC.md §2.2 — implemented verbatim (only `req`'s type
 * is adapted to Next.js 16 Route Handlers, per the controller instructions).
 *
 * NON-NEGOTIABLE (§2.2): `users` (packages/db, §3.2) is the system of
 * record for identity. Auth.js (NextAuth) v5 holds credentials/session
 * material only, in `accounts` / `sessions` / `verification_tokens` /
 * `auth_credentials` (T03 migration) — every one of those tables FKs to
 * `users(id)`, generated by the same `newId()` as every other row in this
 * schema. Cohort assignment (§4/T05) runs synchronously inside `signUp`,
 * on our side, against our `users` row — never in the auth provider's own
 * session/credential tables.
 *
 * Every consumer in this codebase must depend on THIS interface, not on
 * `next-auth` directly — swapping the provider (§12 T03 acceptance) means
 * only files under `lib/auth/` change.
 */
export type UserRole = "member" | "reviewer" | "admin";

export interface AuthenticatedUser {
  id: string; // uuid, FK to users.id
  email: string;
  emailVerified: boolean;
  role: UserRole;
}

export interface AuthProvider {
  getSession(req: NextRequest): Promise<AuthenticatedUser | null>;
  requireUser(req: NextRequest): Promise<AuthenticatedUser>; // throws 401 (ApiError)
  requireRole(req: NextRequest, role: UserRole): Promise<AuthenticatedUser>; // throws 403 (ApiError)
  signUp(email: string, password?: string): Promise<{ userId: string }>;
  sendVerification(userId: string): Promise<void>;
}

const ROLE_RANK: Record<UserRole, number> = { member: 0, reviewer: 1, admin: 2 };

// Verification links expire after 24h. Chosen as a reasonable default for
// V1; revisit if support requests show it's too tight.
const VERIFICATION_TOKEN_TTL_MS = 24 * 60 * 60 * 1000;

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

interface UserRow {
  id: string;
  email: string;
  email_verified_at: string | null;
  role: UserRole;
  deleted_at: string | null;
}

function mapRow(row: UserRow): AuthenticatedUser {
  return {
    id: row.id,
    email: row.email,
    emailVerified: row.email_verified_at !== null,
    role: row.role,
  };
}

async function fetchUserById(id: string): Promise<UserRow | null> {
  const { rows } = await getPool().query<UserRow>(
    `SELECT id, email, email_verified_at, role, deleted_at FROM users WHERE id = $1`,
    [id],
  );
  return rows[0] ?? null;
}

class AuthJsAuthProvider implements AuthProvider {
  async getSession(req: NextRequest): Promise<AuthenticatedUser | null> {
    const secret = process.env.AUTH_SECRET;
    if (!secret) {
      // Fail closed: an unset secret must error loudly, never be treated as
      // "no session => guest" (that would be indistinguishable from a
      // misconfigured deployment silently accepting no auth at all).
      throw new ApiError(500, "AUTH_MISCONFIGURED", "AUTH_SECRET is not configured.");
    }

    const token = await getToken({ req, secret });
    const sub = token?.sub;
    if (!sub) return null;

    const row = await fetchUserById(sub);
    if (!row || row.deleted_at) return null;
    return mapRow(row);
  }

  async requireUser(req: NextRequest): Promise<AuthenticatedUser> {
    const user = await this.getSession(req);
    if (!user) {
      throw new ApiError(401, "UNAUTHENTICATED", "Sign in required.");
    }
    // Acceptance criterion (T03/§12): unverified users cannot access member
    // routes. Every route that calls requireUser (or requireRole, which
    // calls this first) gets this enforced automatically.
    if (!user.emailVerified) {
      throw new ApiError(401, "EMAIL_NOT_VERIFIED", "Please verify your email address first.");
    }
    return user;
  }

  async requireRole(req: NextRequest, role: UserRole): Promise<AuthenticatedUser> {
    const user = await this.requireUser(req);
    // Higher-ranked roles satisfy lower-ranked requirements (admin can hit
    // a reviewer-only route). A same-or-higher check, not an exact match.
    if (ROLE_RANK[user.role] < ROLE_RANK[role]) {
      throw new ApiError(403, "FORBIDDEN", `Requires ${role} role or higher.`);
    }
    return user;
  }

  async signUp(email: string, password?: string): Promise<{ userId: string }> {
    const normalizedEmail = email.trim().toLowerCase();
    if (!EMAIL_RE.test(normalizedEmail)) {
      throw new ApiError(422, "INVALID_EMAIL", "Enter a valid email address.", { field: "email" });
    }
    if (password !== undefined && password.length < 8) {
      throw new ApiError(422, "WEAK_PASSWORD", "Password must be at least 8 characters.", {
        field: "password",
      });
    }

    const pool = getPool();
    const existing = await pool.query(`SELECT id FROM users WHERE email = $1`, [normalizedEmail]);
    if ((existing.rowCount ?? 0) > 0) {
      throw new ApiError(
        422,
        "EMAIL_ALREADY_REGISTERED",
        "An account with this email already exists.",
        { field: "email" },
      );
    }

    // Naive parse — real registrable-domain reduction via the Public Suffix
    // List happens inside assignCohort (T04's classifyEmail). Good enough
    // to populate the NOT NULL email_domain column either way.
    const emailDomain = normalizedEmail.split("@")[1] ?? "";
    const userId = newId();

    // §4.1/T05: cohort assignment runs synchronously, before the user row
    // is persisted. `assignCohort` never throws (NON-NEGOTIABLE §4 — see
    // packages/db/src/cohort-assignment.ts) except for the one outcome that
    // must actually reject the signup: a disposable-domain email never
    // becomes a user row at all.
    const assignment = await assignCohort(normalizedEmail);
    if (assignment.rejected === "disposable") {
      throw new ApiError(422, "DISPOSABLE_EMAIL", "Please use a permanent email address.", {
        field: "email",
      });
    }

    await pool.query(
      `INSERT INTO users (id, email, email_domain, role, tier, cohort_track, organisation_id)
         VALUES ($1, $2, $3, 'member', 'free', $4, $5)`,
      [userId, normalizedEmail, emailDomain, assignment.cohortTrack, assignment.organisationId],
    );

    if (password !== undefined) {
      const passwordHash = await bcrypt.hash(password, 12);
      await pool.query(`INSERT INTO auth_credentials (user_id, password_hash) VALUES ($1, $2)`, [
        userId,
        passwordHash,
      ]);
    }

    return { userId };
  }

  async sendVerification(userId: string): Promise<void> {
    const row = await fetchUserById(userId);
    if (!row) {
      throw new ApiError(404, "USER_NOT_FOUND", "No such user.");
    }

    const token = randomBytes(32).toString("hex");
    const expires = new Date(Date.now() + VERIFICATION_TOKEN_TTL_MS);

    await getPool().query(
      `INSERT INTO verification_tokens (identifier, token, expires) VALUES ($1, $2, $3)`,
      [row.email, token, expires],
    );

    const baseUrl = process.env.PUBLIC_BASE_URL ?? "http://localhost:3000";
    const verifyUrl = `${baseUrl}/api/v1/auth/verify?token=${token}`;
    await sendVerificationEmail(row.email, verifyUrl);
  }
}

export const authProvider: AuthProvider = new AuthJsAuthProvider();

/**
 * Not part of the §2.2 `AuthProvider` interface (the spec's contract has no
 * "verify" method) but colocated here so the provider-swap boundary still
 * holds: `POST /api/v1/auth/verify` depends only on `lib/auth/`.
 */
export async function verifyEmailToken(token: string): Promise<{ userId: string; email: string }> {
  const pool = getPool();
  const { rows } = await pool.query<{ identifier: string; expires: string }>(
    `SELECT identifier, expires FROM verification_tokens WHERE token = $1`,
    [token],
  );
  const record = rows[0];
  if (!record) {
    throw new ApiError(
      422,
      "INVALID_TOKEN",
      "This verification link is invalid or has already been used.",
    );
  }

  // Single-use: consume now regardless of the expiry check below.
  await pool.query(`DELETE FROM verification_tokens WHERE token = $1`, [token]);

  if (new Date(record.expires).getTime() < Date.now()) {
    throw new ApiError(
      422,
      "TOKEN_EXPIRED",
      "This verification link has expired. Please request a new one.",
    );
  }

  const { rows: updatedRows } = await pool.query<{ id: string }>(
    `UPDATE users SET email_verified_at = now()
       WHERE email = $1 AND email_verified_at IS NULL
       RETURNING id`,
    [record.identifier],
  );
  const updated = updatedRows[0];
  if (updated) {
    return { userId: updated.id, email: record.identifier };
  }

  // Already verified (or the user row is gone) — look the user up directly
  // so a re-click of an already-consumed-but-still-valid-looking link
  // (unlikely, since tokens are deleted on use) still resolves sensibly.
  const { rows: existingRows } = await pool.query<{ id: string }>(
    `SELECT id FROM users WHERE email = $1`,
    [record.identifier],
  );
  const existing = existingRows[0];
  if (!existing) {
    throw new ApiError(422, "INVALID_TOKEN", "This verification link is invalid.");
  }
  return { userId: existing.id, email: record.identifier };
}
